- build.gradle
- src/main/java/io/pakland/mdas/githubstats/shell/CustomPromptProvider.java
- src/main/java/io/pakland/mdas/githubstats/shell/components/CommitComponent.java
- src/main/java/io/pakland/mdas/githubstats/shell/components/LinesOfCodeComponent.java
- src/main/java/io/pakland/mdas/githubstats/shell/components/PullRequestComponent.java
Use Spring Shell to turn the application into a CLI.
This is an initial configuration with a provisional package structure. 
As per the [reference](https://docs.spring.io/spring-shell/docs/2.1.2/site/reference/htmlsingle/), this PR adds ShellComponents and Command Registrations (instead of Annotations which are no longer fully supported).
> Implement Spring Shell (CLI)

- src/main/java/io/pakland/mdas/githubstats/domain/model/HistoricQueries.java
- src/main/java/io/pakland/mdas/githubstats/domain/ports/HistoricQueriesRepository.java
Added `HistoricQueries` model.  
Added `HistoricQueriesRepository` repo.  
Closes #25
> feat: historic table and repository

- .github/workflows/jib-container-publish.yml
Closes #6
**Requires @mikededo (repository owner) to:**
- Go to repo Configuration > Secrets
- Set up the DOCKERHUB_USER and DOCKERHUB_TOKEN secrets
This will generate the image and upload it to Dockerhub at repository `githubstats/github-stats:<run_number>` on every PR merged
> ci: create Github Action

- .github/workflows/jib-container-publish.yml
Image was pointing at wrong repository in Dockerhub, and so build fails.
> fix: invalid image name for ci

- src/main/java/io/pakland/mdas/githubstats/domain/model/Team.java
- src/main/java/io/pakland/mdas/githubstats/domain/ports/TeamRepository.java
- src/main/java/io/pakland/mdas/githubstats/domain/service/GetOrganizationFromTeamName.java
- src/test/java/io/pakland/mdas/githubstats/domain/service/GetOrganizationFromIdTest.java
- src/test/java/io/pakland/mdas/githubstats/domain/service/GetOrganizationFromTeamNameTest.java
The user will input the name of our organization, not the ID. Therefore, we have to obtain the organization data given a team id.
> Note: Not sure if I have properly used the `return maybeTeam.get().getOrganization();` since the relation is loaded lazily. AFAIK, it should not be an issue.
Closes #41
> feat: add `getOrganizationFromTeamName` use case

- src/main/java/io/pakland/mdas/githubstats/application/GetOrganizationFromId.java
- src/main/java/io/pakland/mdas/githubstats/application/GetOrganizationFromTeamName.java
- src/main/java/io/pakland/mdas/githubstats/application/exceptions/OrganizationNotFound.java
- src/main/java/io/pakland/mdas/githubstats/application/exceptions/TeamNotFound.java
- src/test/java/io/pakland/mdas/githubstats/domain/service/GetOrganizationFromIdTest.java
- src/test/java/io/pakland/mdas/githubstats/domain/service/GetOrganizationFromTeamNameTest.java
As explained in #51, there are use cases that do not have exceptions thrown because we did not know how to set up the folder structure, and, therefore, where to place the different exceptions.
Closes #51
> fix: add missing exceptions to use cases

- src/main/java/io/pakland/mdas/githubstats/application/AggregateUserReviews.java
- src/main/java/io/pakland/mdas/githubstats/domain/UserReview.java
- src/main/java/io/pakland/mdas/githubstats/domain/UserReviewAggregation.java
- src/main/java/io/pakland/mdas/githubstats/domain/repository/UserReviewRepository.java
- src/test/java/io/pakland/mdas/githubstats/application/AggregateUserReviewsTest.java
- src/test/java/io/pakland/mdas/githubstats/application/GetOrganizationFromIdTest.java
- src/test/java/io/pakland/mdas/githubstats/application/GetOrganizationFromTeamNameTest.java
- src/test/java/io/pakland/mdas/githubstats/application/GetRepositoriesByTeamTest.java
- src/test/java/io/pakland/mdas/githubstats/application/GetTeamsFromOrganizationTest.java
This use case is a bit different from the other use cases as it features the aggregation of entities.
I felt like a class `UserReviewAggregation` was needed to perform the aggregation logic and store the results, and I gave this class a semantic constructor indicating what it was going to do upon instantiation (precisely, aggregating). The use case just runs this aggregation and gets an instance of this class with the results. The logic for each operation is as close to its corresponding entity as possible, with every `UserReview` computing its own line count, and a `UserReviewAggregation` trusting every `UserReview` for running their logic (tell, don't ask).
I don't know if `UserReviewAggregation` really belongs in the model. I guess it might be in the application layer. I certainly …
> feat: add `AggregateUserReviews` use case

- src/main/java/io/pakland/mdas/githubstats/application/SaveOrganization.java
- src/test/java/io/pakland/mdas/githubstats/application/SaveOrganizationTest.java
Added the `SaveRepository` use case. Since we have not defined what to do when entities exist, as a first implementation, I have opted not to save an entity if such exists.
Closes #55.
> feat: add `SaveRepository` use case

- src/main/java/io/pakland/mdas/githubstats/application/dto/TeamDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/adapters/TeamRESTRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/ports/ITeamRESTRepository.java
- src/test/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/TeamRESTRepositoryTest.java
- src/test/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/responses/OrganizationTeams.json
Given an organization name we want to fetch all of its teams from the Github API. In order to do that, I've used the WebClient.
closes #59
> feat: fetch teams from organization user case

- src/main/java/io/pakland/mdas/githubstats/application/FetchPullRequestsFromRepository.java
- src/main/java/io/pakland/mdas/githubstats/application/dto/OrganizationDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/dto/RepositoryDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/dto/TeamDTO.java
- src/main/java/io/pakland/mdas/githubstats/domain/Team.java
- src/main/java/io/pakland/mdas/githubstats/domain/repository/PullRequestExternalRepository.java
- src/main/java/io/pakland/mdas/githubstats/domain/repository/PullRequestRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/PullRequestGitHubRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/controller/UserOptionController.java
- src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/OrganizationGitHubRepositoryTest.java
- src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepositoryTest.java
- src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepositoryTest.java
- Proposal to remove the use of entities on the controller and only manage DTOs. 
- Add the fetch pull requests from a repository use case.
I'll later make a PR removing the use of DTOs as they are holding the same information as our domain entities. There is no need of DTOs under my opinion, also it will reduce the app complexity removing the need of mappers. 
I've analyzed the clean code kata we did on classroom (weather-kata-php) and the teacher didn't use DTOs for the responses of the httpClient.
> feat: `fetchPullRequestsFromRepository` use case

- src/main/java/io/pakland/mdas/githubstats/application/AggregateCommits.java
- src/main/java/io/pakland/mdas/githubstats/domain/CommitAggregation.java
- src/test/java/io/pakland/mdas/githubstats/application/AggregateCommitsTest.java
This use case is very similar to #47.
The suggested changes for #47 by reviewers were applied here as well.
> feat: add `AggregateCommits` use case

- src/main/java/io/pakland/mdas/githubstats/application/FetchAvailableOrganizations.java
- src/main/java/io/pakland/mdas/githubstats/application/FetchPullRequestsFromRepository.java
- src/main/java/io/pakland/mdas/githubstats/application/FetchRepositoriesFromTeam.java
- src/main/java/io/pakland/mdas/githubstats/application/FetchTeamsFromOrganization.java
- src/main/java/io/pakland/mdas/githubstats/application/SaveAllCommits.java
All use cases should be annotated with spring @service, to create a bean component and make them singleton and injectable in other classes.
> fix: add missing @service spring annotation

- src/main/java/io/pakland/mdas/githubstats/application/GetRepositoriesByTeam.java
- src/main/java/io/pakland/mdas/githubstats/application/GetTeamsFromOrganization.java
- src/main/java/io/pakland/mdas/githubstats/domain/Organization.java
- src/main/java/io/pakland/mdas/githubstats/domain/Repository.java
- src/main/java/io/pakland/mdas/githubstats/domain/Team.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/controller/UserOptionController.java
- src/test/java/io/pakland/mdas/githubstats/domain/OrganizationTest.java
- src/test/java/io/pakland/mdas/githubstats/domain/TeamTest.java
- src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/OrganizationGitHubRepositoryTest.java
- src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepositoryTest.java
- Fixed the `Team-Repository` association in the `UserOptionController`.
- Fixed the `Organization-Team` association in the `UserOptionController`.
I opted to override the `hashCode` and `equals` methods using only the `id`
field. The reason is because if done properly, we should not have duplicated
entities and each entity is uniquely identified by the `id` field.
Closes #92
> fix: change entity association in `UserOptionController`

- src/main/java/io/pakland/mdas/githubstats/domain/Commit.java
- src/main/java/io/pakland/mdas/githubstats/domain/CommitAggregation.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommitGitHubRepository.java
- src/main/resources/db/changelog/changes/000_initial_schema.yaml
As @manerow noted on WhatsApp, the lines added and deleted from a commit didn't come in the JSON when you retrieve the PR commit list. It seems that is needed to retrieve every commit individually by its SHA code, and get the additions and deletions from the stats section.
This PR is blocked by #108, because it needs its code to compile.
> feat: request full commit data from pr list

- src/main/java/io/pakland/mdas/githubstats/application/dto/CommentDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/mappers/CommentMapper.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/Comment.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubCommentDTO.java
- src/test/java/io/pakland/mdas/githubstats/application/mappers/CommentMapperTest.java
- Created the GitHubCommentDTO that allows us to parse the response from the GitHub API.
- Added the CommentMapper that allows us to service-agnostically convert the DTO to an Entity.
- Added the CommentMapper to the GitHub repository that was using it.
Closes #121
> fix: remove @JsonProperty from Comment Entity

- src/main/java/io/pakland/mdas/githubstats/application/dto/UserDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/external/FetchUsersFromTeam.java
- src/main/java/io/pakland/mdas/githubstats/application/mappers/UserMapper.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/User.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubUserDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepository.java
- src/test/java/io/pakland/mdas/githubstats/application/mappers/UserMapperTest.java
- Created the `GitHubUserDTO` that allows us to parse the response from the GitHub API.
- Added the `UserMapper` that allows us to service-agnostically convert the `DTO` to an `Entity`.
- Added the `UserMapper` to the GitHub repository that was using it.
> fix: remove `JsonProperty` from `User` entity

- src/main/java/io/pakland/mdas/githubstats/application/dto/TeamDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/mappers/TeamMapper.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/Team.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubTeamDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepository.java
- src/test/java/io/pakland/mdas/githubstats/application/mappers/TeamMapperTest.java
- Created the `GitHubTeamDTO` that allows us to parse the response from the GitHub API.
- Added the `TeamMapper` that allows us to serice-agnostically convert the `DTO` to an `Entity`.
- Added the `TeamMapper` to the GitHub repository that required it.
Closes #135 
> I incorrectly named the branch...
> fix: remove `JsonProperty` from `Team` entity

- src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapper.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequest.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/PullRequestGitHubRepository.java
- src/test/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapperTest.java
- Created the `GitHubPullRequestDTO` that allows us to parse the response from the GitHub API.
- Added the `PullRequestMapper` that allows us to serice-agnostically convert the DTO to an Entity.
- Added the `PullRequestMapper` to the GitHub repository that required it.
Closes #131
> This should be merged after #136.
> fix: remove `JsonProperty` from `PullRequest`

- src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestStateDTO.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequestState.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestStateDTO.java
- Created `GitHubPullRequestStateDTO` that allows us to parse the response from the GitHub API
- Use such DTO inside the `GitHubPullRequestDTO`
Closes #132 
> This should be merged afetr #137
> fix: remove `JsonProperty` from `PullRequestState` 

- src/main/java/io/pakland/mdas/githubstats/application/dto/RepositoryDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/mappers/RepositoryMapper.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/Repository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubRepositoryDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/RepositoryGitHubRepository.java
- src/test/java/io/pakland/mdas/githubstats/application/mappers/RepositoryMapperTest.java
- Created `GitHubRepositoryDTO` that allows us to parse the response from the GitHub API
- Added the `RepositoryMapper` that allows us to serice-agnostically convert the DTO to an Entity.
- Added the `RepositoryMapper` to the GitHub repository that required it.
Closes #130 
> This should be merged after #139
> fix: remove `JsonProperty` from `Repository`

- src/main/java/io/pakland/mdas/githubstats/application/dto/CommentDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/dto/CommitDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/external/FetchCommentsFromPullRequest.java
- src/main/java/io/pakland/mdas/githubstats/application/mappers/CommentMapper.java
- src/main/java/io/pakland/mdas/githubstats/application/mappers/CommitMapper.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/Comment.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/Commit.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/CommitAggregation.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequest.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequestAggregation.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/UserReview.java
- src/main/java/io/pakland/mdas/githubstats/domain/repository/CommentExternalRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubUserController.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubCommentDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubCommitDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommentGitHubRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommitGitHubRepository.java
- src/test/java/io/pakland/mdas/githubstats/application/external/FetchCommitsFromPullRequestTest.java
- src/test/java/io/pakland/mdas/githubstats/application/internal/AggregateUserReviewsTest.java
- `fetchCommentsFromPullRequest` use case.
- change the way we obtain the number of lines added/deleted. As stated in classroom, we should obtain them from the pull request object instead of the commit object.
- Small refactor of code implied with the lines additions and deletions.
closes #141
> feat: fetch comments from pull request

- src/main/java/io/pakland/mdas/githubstats/domain/entity/Commit.java
- src/main/java/io/pakland/mdas/githubstats/domain/lib/InternalCaching.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestStateDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommentGitHubRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommitGitHubRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/OrganizationGitHubRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/PullRequestGitHubRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/RepositoryGitHubRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepository.java
- src/test/java/io/pakland/mdas/githubstats/domain/entity/CSVTest.java
- src/test/java/io/pakland/mdas/githubstats/domain/entity/CommitAggregationTest.java
- src/test/java/io/pakland/mdas/githubstats/domain/entity/OrganizationTest.java
- src/test/java/io/pakland/mdas/githubstats/domain/entity/PullRequestAggregationTest.java
- src/test/java/io/pakland/mdas/githubstats/domain/entity/TeamTest.java
- src/test/java/io/pakland/mdas/githubstats/domain/entity/UserReviewAggregationTest.java
- src/test/java/io/pakland/mdas/githubstats/domain/entity/UserTest.java
- src/test/java/io/pakland/mdas/githubstats/domain/lib/InternalCachingTest.java
- Added an internal cache to avoid executing the same query when there are many teams in the same repository. This requests the same pull requests for each team, which translates on fetching the same comments and commits which is a really demanding task.
- Added logged so that we are aware of what is being done in the background. We can add an option to make it silent by default.
- Other minor improvements.
> feat: major improvements on efficiency

- src/main/java/io/pakland/mdas/githubstats/application/dto/UserReviewDTO.java
- src/main/java/io/pakland/mdas/githubstats/application/external/FetchCommentsFromPullRequest.java
- src/main/java/io/pakland/mdas/githubstats/application/external/FetchReviewsFromPullRequest.java
- src/main/java/io/pakland/mdas/githubstats/application/mappers/ReviewMapper.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/UserReview.java
- src/main/java/io/pakland/mdas/githubstats/domain/repository/CommentExternalRepository.java
- src/main/java/io/pakland/mdas/githubstats/domain/repository/ReviewExternalRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubUserController.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubReviewDTO.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommentGitHubRepository.java
- src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/ReviewGitHubRepository.java
- Given a pull request, fetch all of its reviews.
- For the moment i'm only mapping the "id" of the review. We should analyze how we want to fetch also the user it belongs to and its team to compute the reviews inside/outside the team metrics.
- Small refactor to the comment use case to call the repository with a dto request object
Closes #152
> feat: `fetchReviewsFromPullRequest` use case

- src/main/java/io/pakland/mdas/githubstats/application/internal/AggregateReviews.java
This is a proposal to #168 in which we keep the structure of `Organization` -> `Team` -> `User`.
> I also changed the way we work with maps. Instead of using the `getKey()` method and then having to access the value of the key through the `get()` method, we simply use the `entrySet()` method which allows us to access at the `key` and `value` at the same time.
> [PROPOSAL] feat: alternative to `Review`s per user

- src/main/java/io/pakland/mdas/githubstats/application/internal/MetricCsvExporter.java
- src/main/java/io/pakland/mdas/githubstats/application/internal/MetricExporter.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/CSVExportable.java
- src/main/java/io/pakland/mdas/githubstats/domain/entity/Metric.java
Export Metriics to a certain format. In this case is CSV. The `MetricCsvExporter::export` method will export an array of metric objects to a .csv file into the filesystem on the defined path. We must declare the resulting file name in the defined path (this is subject to change if we decide we want to set a default file name).
Closes #170
> Feat: export array of `Metric` to csv file
